### PR TITLE
Adding Descriptions #7

### PR DESCRIPTION
**Pull request by Toltar**
Added Descriptions for the included Atom Commands.

Fixed a few descriptions that needed to be fixed. Please suggest any grammar or spelling errors. Or even if it needs to be shortened or better written.

### CODE REVIEW

**Comment by nwinkler** [comment]
Awesome, thanks!

**Comment by nwinkler** [comment]
Closes #7

**Comment by nwinkler** [comment]
Fixes #7

**Comment by Toltar** [comment]
No prob dude :-)

**Pull request merged**
